name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  IMAGE_TAGS: |
    type=schedule
    type=semver,pattern={{version}}
    type=semver,pattern={{major}}.{{minor}}
    type=semver,pattern={{major}}
    type=ref,event=branch
    type=ref,event=pr
    type=sha

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.0.0
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0
    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v4.0.1
      with:
        images: eepokt/chain-healthcheck-sidecar
        tags: ${{ env.IMAGE_TAGS }}
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      if: ${{ github.ref_name == 'master' }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.0.0
      if: ${{ github.ref_name == 'master' }}
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

